### ISSUE TITLE
Input required and not supplied: tag

### ISSUE THREAD

**Issue by smistad** [svenstaro/upload-release-action#111]
I am suddenly getting this error: **Input required and not supplied: tag** 
It happens everytime I try to use this action, even though the workflow file contains:  tag: ${{ github.ref }}
This worked fine a couple of months ago, I have not changed anything in the workflow file.

**Comment by mikevoyt** [comment]
I just started seeing the same thing when using `tag: ${{ github.ref }}`

I also tried removing `tag` (to use the defaults) and got the same error.

**Comment by svenstaro** [comment]
Is this some GitHub API change or something? I don't have much time right now but if someone figures it out, I'll try to push a fixed release.

**Comment by mikevoyt** [comment]
Hmm weird I kicked off another build and it worked this time.  Maybe a race condition?

**Comment by svenstaro** [comment]
Has this occurred again? Otherwise I'd close this.

**Comment by smistad** [comment]
For me it happened for every release build last week. 6 different workflows all failed with the same error.

**Comment by elden1337** [comment]
+1, error seems constant.

**Comment by svenstaro** [comment]
So is `${{ github.ref }}` even set for you? Could you print it and check?

**Comment by elden1337** [comment]
> So is `${{ github.ref }}` even set for you? Could you print it and check?

Hmm, it doesn't seem so? I'm really not good with yml-programming but these logpatterns tell me that there should be a secondary line with the result?

```yml
##[debug]..Evaluating Index:
##[debug]....Evaluating github:
##[debug]....=> Object
##[debug]....Evaluating String:
##[debug]....=> 'workspace'
##[debug]..=> '/home/runner/work/hass-peaq/hass-peaq'
##[debug]=> '/home/runner/work/hass-peaq/hass-peaq/custom_components/peaqev/peaqev.zip'
##[debug]Result: '/home/runner/work/hass-peaq/hass-peaq/custom_components/peaqev/peaqev.zip'
##[debug]Evaluating: github.ref
##[debug]Evaluating Index:
##[debug]..Evaluating github:
```

**Comment by elden1337** [comment]
Is there any other input I can help with? I thought there was something wrong with the ui-create release but tags are created fine.

**Comment by elden1337** [comment]
ok an update of the checkout repo from was needed, now on v3.3.0 and that seems to be working.

        name: Check out repository
        uses: actions/checkout@v3.3.0

Thanks for your support Sven.

**Comment by svenstaro** [comment]
Ok cool, can we consider this fixed then?

**Comment by mikevoyt** [comment]
Hmm oddly I just randomly hit this again today, even with `checkout@v3.3.0`  and I've been building just fine for the past few weeks:

```
Run svenstaro/upload-release-action@2.7.0
  with:
    repo_token: ***
    file: ./app/package/*.tar.gz
    overwrite: true
    file_glob: true
Error: Input required and not supplied: tag
```

**Comment by edgarrmondragon** [comment]
Started running into this today:

```
##[debug]Evaluating: github.ref
##[debug]Evaluating Index:
##[debug]..Evaluating github:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'ref'
##[debug]=> ''
##[debug]Result: ''
##[debug]Loading env
Run svenstaro/upload-release-action@v2
  with:
    repo_token: ***
    file: dist/*.whl
    overwrite: true
    file_glob: true
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.10.13/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.10.13/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.13/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.13/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.13/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.13/x64/lib
Error: Input required and not supplied: tag
```

**Comment by maks-rafalko** [comment]
Got the same today: https://github.com/infection/infection/actions/runs/6208387910/job/16854598976#step:8:12

Even though `tag` is present in the workflow: 

https://github.com/infection/infection/blob/0614737337055fd84a9a0840c2c2bf9bd8107063/.github/workflows/release.yaml#L55-L59

**Comment by maks-rafalko** [comment]
Found: in my case it didn't work because of `on` trigger event being `release` instead of `tags push`:

https://github.com/infection/infection/commit/5019cdc8d707ddacffbe991a1c12c8e8e348845f

However, on other repositories, it works event with 

```yaml
on:
  release:
    types: [ created ]
```

**Comment by mikevoyt** [comment]
Interesting, yes it failed for me when using:

```
on:
  release:
    types: [ published ]
```

**Comment by apprehensions** [comment]
failing for me too with
```yaml
on:
  release:
    types: [ created ]
```

**Comment by harrysarson-signaloid** [comment]
I see this behaviour (`${{ github.ref }}` not being set [1] when creating a release from an existing tag. Creating a release from a non-existing tag (and so github creates both the tag and the release together) works okay.

[1]: My trigger is

  ```
  on:
    release:
      types: [published]
  ```
