### ISSUE TITLE
Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by MHSanaei** [svenstaro/upload-release-action#120]
i got this warning today 
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: svenstaro/upload-release-action@2.7.0. For more information ...

I saw your last commit [Update to Node20](https://github.com/svenstaro/upload-release-action/commit/a4bae284e7796b6c439e4b4f40712965fb722cc0)
Please if you can release an update for us.

thank you

**Comment by MHSanaei** [comment]
I just made a fork and updated it for personal use. 
Use this if you need it until he comes back. 
https://github.com/MHSanaei/upload-release-action

**Comment by svenstaro** [comment]
Will do a release soon.

**Comment by svenstaro** [comment]
Here we go.
