### ISSUE TITLE
specify release name

### ISSUE THREAD

**Issue by benswift** [svenstaro/upload-release-action#14]
Currently the asset name is specified with `asset_name`, but the actual release itself doesn't get a name & body (description). The GH web view _does_ display a title & description based on the first line & rest of the commit message respectively, but the API returns null

This is ok (once you know how it works) but it'd be nice if there was a `release_name` (and even optional `release_argument` options for this action to set those as well. Is that a possibility? Or does the octokit lib not make that easy?

**Comment by svenstaro** [comment]
Good point. If you made a PR for this, I'd surely accept it.

**Comment by benswift** [comment]
Sure, ok, thanks. I made a start - but need to check a couple of things before I create the PR. Sorry about the delay.
