### ISSUE TITLE
release_name does not seem to apply

### ISSUE THREAD

**Issue by Spikatrix** [svenstaro/upload-release-action#26]
Thank you for creating this very useful action!

Everything works as I'd like it to, except that it doesn't seem to pick up the `release_name` I've specified in the workflow file. The release name I get is the default tag name.

[Here is my workflow file](https://github.com/Spikatrix/Zoned/actions/runs/229669899/workflow) (See the last two jobs). I get `v-dev` as the name of the release instead of the specified one. Am I doing something wrong here?

**Comment by kittaakos** [comment]
@Spikatrix, can you please verify my [proposed fix](https://github.com/svenstaro/upload-release-action/pull/27)?  Please use `uses: kittaakos/upload-release-action@GH-26`, thanks!

**Comment by Spikatrix** [comment]
@kittaakos Your fix works! Thank you!
