### ISSUE TITLE
asset_name seems to be required

### ISSUE THREAD

**Issue by tcurdt** [svenstaro/upload-release-action#28]
But the docs state it differently

> Optional Arguments
> 
> asset_name: The name the file gets as an asset on a release. Use $tag to include the tag name. When not provided it will default to the filename. This is not used if file_glob is set to true.

```
Run svenstaro/upload-release-action@v1-release
  with:
    repo_token: ***
    file: target/project-linux-x86_64-gnu.tgz
    tag: latest
  env:
    project: project
##[error]Input required and not supplied: asset_name
```

**Comment by svenstaro** [comment]
You seem to be using `v1`. Try using `v2`. :)

**Comment by tcurdt** [comment]
Ups. Sorry about that.
