### ISSUE TITLE
Allow using glob patterns to upload

### ISSUE THREAD

**Issue by cilerler** [svenstaro/upload-release-action#3]
Allow using glob patterns to upload.

e.g.
```
$(Build.ArtifactStagingDirectory)/**/*.nupkg;
!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg
```

**Comment by cilerler** [comment]
Is that supports multiple patterns with a semicolon? Such as `$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg`

**Comment by svenstaro** [comment]
Should be possible. See [here](https://www.npmjs.com/package/glob).
