### ISSUE TITLE
Uploading executable binary file

### ISSUE THREAD

**Issue by Tejas2805** [svenstaro/upload-release-action#43]
I am trying to upload an executable binary file to release but it is getting uploaded as a normal file and not as an executable. Any help on how to fix it? Or is it not possible to do?

**Comment by jrhunger** [comment]
Does it behave differently if you upload it manually?  
Whether a binary file is "executable" depends on your browser's settings and the server-provide mime-type and/or file extension.
I think binary files attached to releases always download with mime type application/octet-stream (small sample set, i could be very wrong), in which case maybe the file extension has more say in determining how your client treats it.

**Comment by Tejas2805** [comment]
There was an error on my part. It Works!
