### ISSUE TITLE
Body - Read text from a file

### ISSUE THREAD

**Issue by pranjal-joshi** [svenstaro/upload-release-action#48]
Hello, Thanks for the great action!
Is there any way supported to get the `body` string from the file which is present in the repo?
So that this file can be changed for release description and committed to creat a new releases with dynamic bodies.

**Comment by pranjal-joshi** [comment]
This have been achieved by using env variable to read file and use it with your action.
Closing.

**Comment by svenstaro** [comment]
Perhaps you could make a PR for an example in the readme to allow this use case?
