### ISSUE TITLE
[BUG] All release tags are created on master

### ISSUE THREAD

**Issue by Aytackydln** [svenstaro/upload-release-action#63]
I want my dev branch to make prereleases but it still creates the release tags on master. This step should specify branch or commit while releasing.

target_commitish needs to be specified while making release. This can be an optional parameter, too.

**Comment by illusion0001** [comment]
I think this is what #46 is solving, but it has not been merged yet

**Comment by Hiroshiba** [comment]
I faced the same issue.
The proposed [pull request](https://github.com/svenstaro/upload-release-action/pull/46) does indeed seem to solve this issue.
I hope you merge them! @svenstaro
