### ISSUE TITLE
Resource not accessible by integration

### ISSUE THREAD

**Issue by OctonalXX** [svenstaro/upload-release-action#70]
When I try to upload some binaries to github, it outputs:
 `Resource not accessible by intergration`
What did I do wrong?
https://github.com/OctonalXX/shulker-dupe-auto/runs/6060142867?check_suite_focus=true

**Comment by OctonalXX** [comment]
Oh, I see. You need to set permissions

**Comment by metasim** [comment]
@OctonalXX Which permissions end up being needed?

**Comment by yurishkuro** [comment]
@metasim we just ran into similar issue, and it was the write permission under Settings | Actions | General that was needed:
![image](https://user-images.githubusercontent.com/3523016/199314484-8ce93ff8-8ef9-49d9-a30e-47f8cdcfa2f7.png)

**Comment by edgarrmondragon** [comment]
I'm using granular permissions, so this allowed my workflow to upload files to the release:

```yaml
permissions:
  contents: write
```

**Comment by svenstaro** [comment]
Would you like to add that to the README?

**Comment by edgarrmondragon** [comment]
> Would you like to add that to the README?

Sure, I'll send you a PR 🙂
