### ISSUE TITLE
Optional arguments seems to be required

### ISSUE THREAD

**Issue by sigmaSd** [svenstaro/upload-release-action#73]
If I don't specify tag or repo_token the action complains with `Error: Input required and not supplied: tag`

**Comment by sigmaSd** [comment]
I see it was added here https://github.com/svenstaro/upload-release-action/commit/7d269bd7122a9532697e0e48d3d8a6495e7d7ae8 maybe its just not released?

**Comment by svenstaro** [comment]
Should be released now, thanks for the nudge. Please test. :)

**Comment by sigmaSd** [comment]
works, thanks for this nice project!
