### ISSUE TITLE
Node 12 is deprecated

### ISSUE THREAD

**Issue by nhuet** [svenstaro/upload-release-action#81]
Github is now recommending to switch to node 16. Do you plan upgrading node version in a future (but not too far) release?

See https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/ for more details.

**Comment by Vucko130** [comment]
Same. I am getting this warning message too. 

Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: svenstaro/upload-release-action

**Comment by SCP-017** [comment]
@svenstaro

**Comment by justinjeffery-ipf** [comment]
Looks like a PR is open: https://github.com/svenstaro/upload-release-action/pull/83

**Comment by wingkwong** [comment]
+1

**Comment by techyCoder81** [comment]
+1

**Comment by tarampampam** [comment]
Friendly ping @svenstaro

**Comment by svenstaro** [comment]
I'll take care of it soon.

**Comment by tarampampam** [comment]
18 days later: Friendly ping @svenstaro again 🥲

**Comment by svenstaro** [comment]
I'm currently in the process of rewriting the action and updating it in the process. I'm not much a fan of the current structure anyway. At any rate, it's not much code and shouldn't take too long.

**Comment by adrianinsaval** [comment]
@svenstaro any news? could you also take a look at #82 and #76 ?

**Comment by thunder-coding** [comment]
Node 12 turning EOL is the only reason why I forked this repo here https://github.com/termux/upload-release-action. Currently targets v16 of Nodejs. Soon planning to update to v18 after dependency upgrades.

NOTE: Also has some breaking changes. Consider going through the v3 changelog first
