### ISSUE TITLE
The `set-output` command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by darthdeus** [svenstaro/upload-release-action#82]
Similarly to #81 

> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by Vucko130** [comment]
yeah suddenly faced the same

**Comment by wingkwong** [comment]
+1

**Comment by E85Addict** [comment]
+1

**Comment by techyCoder81** [comment]
+1

**Comment by hong0980** [comment]
+1

**Comment by alex-sandrk** [comment]
+1

**Comment by fballiano** [comment]
+1

**Comment by shawaj** [comment]
#86 fixes this
