### ISSUE TITLE
Error saving asset

### ISSUE THREAD

**Issue by rainjm** [svenstaro/upload-release-action#9]
The first few times can run normally, and suddenly reported an error.
My friend encountered the same problem.

[build-openwrt.yml](https://github.com/rainjm/OpenWrt-K2P-firmware/blob/master/.github/workflows/build-openwrt.yml)

![image](https://user-images.githubusercontent.com/9592236/75628416-b50ec700-5c13-11ea-8bee-e7603d2fc857.png)
![image](https://user-images.githubusercontent.com/9592236/75628419-bfc95c00-5c13-11ea-8cb8-690e05bc5300.png)

**Comment by svenstaro** [comment]
Seems to be a GitHub issue to me. Does it work now?

**Comment by rainjm** [comment]
I tried twice without errors
