### ISSUE TITLE
[bug] failed to upload/skip files that are 0 byte

### ISSUE THREAD

**Issue by Loyalsoldier** [svenstaro/upload-release-action#94]
[Task link](https://github.com/Loyalsoldier/v2ray-rules-dat/actions/runs/4122883129/jobs/7120210407)

```shell
Error: Validation Failed: {"resource":"ReleaseAsset","code":"custom","field":"size","message":"size must be greater than or equal to 1"}
```

**Comment by svenstaro** [comment]
Did you check whether the GitHub API allows for empty files?

**Comment by Loyalsoldier** [comment]
The error message `size must be greater than or equal to 1` does not appear in this repo source code. I think it comes from the GitHub API. So maybe to provide an option for users to throw an error or skip uploading empty files?

**Comment by svenstaro** [comment]
I'd be happy if you added a thing to this action to make people aware of empty files.

**Comment by Loyalsoldier** [comment]
> I'd be happy if you added a thing to this action to make people aware of empty files.

I have created a PR( #102 ) to fix this issue, could you take a look?
