### ISSUE TITLE
Glob fails as of 2.4.1

### ISSUE THREAD

**Issue by Dico200** [svenstaro/upload-release-action#95]
I noticed the glob package version was downgraded from "^8" to "^7" in release 2.4.1.
This seems to have led to an issue where the glob I'm using no longer works.
The syntax I'm using is:

`C:/path/to/file1.txt,C:/path/to/file2.zip,C:/path/to/file3.yml`

As of 2.4.1 (I'm tagging the action as `@v2` in my workflow) it fails, saying the glob didn't match any files. 
I triple checked and the logged file paths match existing files on my self-hosted CI machine (running Windows 10).

I don't mind pinning the version to 2.4.0, but I thought I'd let you know about what seems like a regression 🙂

**Comment by svenstaro** [comment]
Should be fixed in https://github.com/svenstaro/upload-release-action/pull/105.
